Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
    path('users/', include('users.urls')),
]

pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu', views.menu, name='menu'),
    path('menu/<int:pizza_id>', views.pizza, name='pizza'),
    path('new_pizza/', views.new_pizza, name='new_pizza'),
    path('new_topping/<int:pizza_id>/', views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>/', views.edit_topping, name='edit_topping'),
    path('comments/<int:pizza_id>/', views.comments, name='comments'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return f"{self.name[:50]}..."


class Comment(models.Model):
    comment = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms
from .models import Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        lable = {'name: ':''}
    
class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        lable = {'name: ':''}
        widgets = {'name':forms.Textarea(attrs={'cols':80})}
        
    

pizzas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Pizza, Comment
from .forms import PizzaForm,ToppingForm
from django.http import Http404

# Create your views here.

def index(request):
    '''The home page for pizzeria'''
    return render(request, 'pizzas/index.html')

@login_required
def menu(request):
    menu = Pizza.objects.order_by('date_added')

    context = {'menu': menu}

    return render(request,'pizzas/menu.html', context)

@login_required
def pizza(request,pizza_id):

    pizza = Pizza.objects.get(id=pizza_id)
    Toppings = pizza.topping_set.order_by('-date_added')
  

    context = {'pizza': pizza, 'Toppings': Toppings}
    return render(request, 'pizzas/pizza.html',context)

def new_pizza(request):
    if request.method != 'POST': 
        form = PizzaForm()

    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            new_pizza = form.save(commit=False)
            new_pizza.owner = request.user
            new_pizza.save() # save to database directly

            return redirect("pizzas:menu")
    context= {'form':form}
    return render(request, "pizzas/new_pizza.html", context)

@login_required
def new_topping(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if pizza.owner != request.user:
        raise Http404

    if request.method !='POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)

        if form.is_valid():
            new_topping = form.save(commit=False) 
            new_topping.pizza = pizza
            new_topping.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    
    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_topping.html', context)

@login_required
def edit_topping(request, topping_id):
    toppings = Toppings.objects.get(id=topping_id)
    pizza = toppings.pizza

    if pizza.owner != request.user:
        raise Http404

    if request.method !='POST':
        form = ToppingForm(instance=toppings)
    else:
        form = ToppingForm(instance=toppings, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    
    context = {'toppings': toppings, 'pizza':pizza,'form': form}
    return render(request, 'pizzas/edit_topping.html', context)

def comments(request,pizza_id):
    if request.method != 'POST' and request.POST.get('btn1'):
        comment = request.POST.get('comment')
        Comment.objects.create(pizza_id=pizza_id, username=request.user, text=comment, date_added=date.today)
        comments = Comment.objects.filter(pizza=pizza_id)
        pizza = Pizza.objects.get(id=pizza_id)

        context = {'pizza':pizza, 'comments': comments}
        return render(request, 'pizzas/comments.html',context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method !='POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('MainApp:index')
    
    context = {'form': form}
    return render(request,'registration/register.html',context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a>
    <a href="{% url 'pizzas:menu' %}">Menu</a>
    {% if user.is_authenticated %}
    Hello, {{user.username}}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}

{% block content%}

<h2>
    <p> Pizza: {{ pizza }}</p>
</h2>
<h2>
    <p><img src="{{post.image.url}}" class="img-thumbnail" style="max-height:300px;" alt="No image"><br><br></p>
</h2>

<ul>
    <form method="POST">
        {% csrf_token %}
        {% for c in comments %}
        <li>
            <p>{{c.text}} &nbsp -- &nbsp {{c.username}}</p>
        </li>
        {% empty %}
        <li> There are no comments for this product.</li>
        {% endfor %}

        <p><input type="text" name="comment"></p>
        <p><button type="submit" name="btn1" value=1>Submit Comment</button></p>

    </form>
</ul>

{% endblock content %}

pizzas/templates/pizzas/edit_topping.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}"> {{ pizza }}</a></p>


<p>Edit topping:</p>

<form action="{% url 'pizzas:edit_topping' topping.id%}" method="post">


    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit"> save change</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>
    Welcome to Pizza World. You can order the pizza you like.
</p>

{% endblock content %}

pizzas/templates/pizzas/menu.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Menu</p>

<ul>
    {% for p in menu %}

    <li>
        <a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a>
    </li>

    {% empty %}
    <li>No pizza have been added yet.</li>

    {% endfor %}

</ul>

<a href="{% url 'pizzas:new_pizza'%}">Add a new pizza</a>


{% endblock content %}

pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %}



{% block content %}

<p>Add a new pizza:</p>

<form action="{% url 'pizzas:new_pizza' %}" method="post">


    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit"> Add pizza</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}



{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}"> {{ pizza }}</a></p>


<p>Add a new topping:</p>

<form action="{% url 'pizzas:new_topping' pizza.id%}" method="post">


    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit"> Add topping</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{%block content %}

<p>Pizza: {{ pizza }}</p>


<ul>
    {% for toppings in Toppings %}
    <li>
        <p>{{toppings.date_added|date:'M d, Y H:i' }}</p>
        <p>{{toppings.name|linebreaks}}</p>
    </li>

    {% empty %}
    <li> There are no toppings for this pizza yet.</li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'pizzas:new_topping' pizza.id %}">Add new topping</a>
</p>

{% endblock content %}